id: csv_importer_asset
label: Asset CSV Import
description: Default group for asset CSV import.
source_type: CSV

## Here we add any default configuration settings to be shared among all
## migrations in the group. For this example, the source tables are in the
## Drupal (default) database, but usually if your source data is in a
## database it will be external.
#shared_configuration:
#  # Specifying 'source' here means that this configuration will be merged into
#  # the 'source' configuration of each migration.
#  source:
#    # A better practice for real-world migrations would be to add a database
#    # connection to your external database in settings.php and reference its
#    # key here.
#    key: default
dependencies:
  enforced:
    module:
      - csv_importer
