label: 'Base Asset CSV importer'
migration_tags:
  - 'Drupal 9'
  - 'Farm OS'
  - 'Asset'
  - 'CSV Importer'
migration_group: csv_importer_asset
id: csv_importer_farm_asset_base
deriver: Drupal\csv_importer\Plugin\migrate\AssetDeriver
dependencies:
  enforced:
    module:
      - asset
source:
  plugin: csv
  path: 'modules/custom/csv_importer/kk.csv'
  ids:
    - id
  column_names:
    0:
      id: 'id'
process: {  }
destination:
  plugin: 'entity:asset'
migration_dependencies:
  required: {  }
  optional: {  }
